configVersion: 1

settings:
  java: "&8[&aJava&8]"
  unknown: "&8[&aUnknown&8]"
  android: "&8[&aAndroid&8]"
  ios: "&8[&bI&fOS&8]"
  osx: "&8[&fOS&bX&8]"
  fireos: "&8[&6F&FireOS&8]"
  gearvr: "&8[&7Gearf&VR8]"
  hololens: "&8[&7Holo&fLens&8]"
  win10: "&8[&3WIN10&8]"
  win32: "&8[&3Win&f32&8]"
  dedicated: "&8[&aDED&8]"
  orbis: "&8[&3ORBIS&8]"
  nx: "&8[&eNX&8]"
  switch: "&8[&4Switch&8]"
  xboxOne: "&8[&2Xbox&fOne&8]"
