configVersion: 1

settings:
  java: ""
  unknown: ""
  android: "&8[&aAND&8]"
  ios: "&8[&bI&fOS&8]"
  osx: "&8[&fOS&bX&8]"
  fireos: "&8[&6F&fOS&8]"
  gearvr: "&8[&7G&fVR&8]"
  hololens: "&8[&7M&fHL&8]"
  win10: "&8[&3WIN&8]"
  win32: "&8[&3W&f32&8]"
  dedicated: "&8[&aDED&8]"
  orbis: "&8[&3ORB&8]"
  nx: "&8[&eNX&8]"
  switch: "&8[&4SWT&8]"
  xboxOne: "&8[&2X&fBX&8]"