name: FloodgatePlaceholder
description: FloodgatePlaceholder.
version: 1.0
main: com.rngservers.floodgateplaceholder.FloodgatePlaceholder
depend: [floodgate-bukkit]
softdepend: [PlaceholderAPI]
author: RandomUnknown

commands:
  floodgateplaceholder:
    description: FloodgatePlaceholder info
    default: true
    usage: /floodgateplaceholder
    aliases: [fgp]

permissions:
  floodgateplaceholder.reload:
    default: op
    description: Reload FloodgatePlaceholder